### ISSUE TITLE
Analyze the Meditron model evaluation environment and use open source tools

### ISSUE THREAD

**Issue by dionis** [dionis/SpanishMedicaLLM#12]
**Subtask**

- Study the evaluation forms of the Meditron Model and the scripts proposed by the creators.
- Study how to use Medplexity for is a python library to help with evaluation of LLMs for medical applications. 
It provides easy interfaces to use existing benchmarks, including MedQA, PubMedQA, etc. and evaluate performance of LLMs and more complex chains on these benchmarks. https://medplexity.readthedocs.io/en/latest/.

- Create simple examples (50) that allow taking the output of the trained models and being evaluated with frameworks for testing LLM medical models.

**Expected Result:** 

Scripts and documents that allow us to understand and automate the testing process for models trained for Spanish in the medical context.

**Comment by Alvaro8gb** [comment]
the anylis are added
