### ISSUE TITLE
Find benchmark evaluation  for LLM models  on medical context in Spanish

### ISSUE THREAD

**Issue by dionis** [dionis/SpanishMedicaLLM#13]
Find one or several test sets to evaluate the generative output of LLM trained in medical contexts.

**Note:** It would be desirable for them to be directly in Spanish or to have been built for that purpose to avoid automatic translation.

If you find benchmark that have been automatically translated from English sources, do not discard them and take them into account.

**Resources to consult:**
    BioMistral: A Collection of Open-Source Pretrained Large Language Models for Medical Domains.

    Pretrained biomedical language models for clinical NLP in Spanish.

    Spanish Pre-Trained Language Models for HealthCare Industry.

    A Survey of Spanish Clinical Language Models.

**Expected results:**
- Set for testing models trained in a medical context for Spanish.
- A readme on markdown format with details of research process.

**Comment by Alvaro8gb** [comment]
the benchmarks are added
