### ISSUE TITLE
Build and evaluation corpus from Spain medical test repository

### ISSUE THREAD

**Issue by dionis** [dionis/SpanishMedicaLLM#18]
From the website: 
   https://fse.mscbs.gob.es/fseweb/view/public/datosanteriores/cuadernosExamen/busquedaConvocatoria.xhtml

extract information associated to question and request and create a framework for evaluation following the Meditron guidelines in model evaluation. 
 
-  Check if exist similar repositories in LATAM cuntries as Chili, Argentina, Mexico, Uruguay.
 
- Check copywrite licences and create document with dataset features. 

- Create a csv, readme and python script files as output.

**Comment by Alvaro8gb** [comment]
We have to meet with the team to define wich task we are going to evaluate
